# Generated by Django 5.2.3 on 2025-06-28 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدورة')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الدورة')),
                ('description', models.TextField(blank=True, verbose_name='وصف الدورة')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'دورة',
                'verbose_name_plural': 'الدورات',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_card_number', models.CharField(max_length=20, unique=True, verbose_name='رقم البطاقة')),
                ('rank', models.CharField(max_length=50, verbose_name='الرتبة')),
                ('full_name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('unit', models.CharField(max_length=100, verbose_name='الوحدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'طالب',
                'verbose_name_plural': 'الطلاب',
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('is_completed', models.BooleanField(default=False, verbose_name='مكتملة')),
                ('handwritten_report', models.ImageField(blank=True, null=True, upload_to='handwritten_reports/', verbose_name='تقرير بخط اليد')),
                ('course_photo', models.ImageField(blank=True, null=True, upload_to='course_photos/', verbose_name='صورة الدورة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institute_app.course', verbose_name='الدورة')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='institute_app.student', verbose_name='الطالب')),
            ],
            options={
                'verbose_name': 'تسجيل',
                'verbose_name_plural': 'التسجيلات',
                'unique_together': {('student', 'course')},
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المادة')),
                ('code', models.CharField(max_length=20, verbose_name='كود المادة')),
                ('max_grade', models.PositiveIntegerField(default=100, verbose_name='الدرجة القصوى')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='institute_app.course', verbose_name='الدورة')),
            ],
            options={
                'verbose_name': 'مادة',
                'verbose_name_plural': 'المواد',
                'unique_together': {('course', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_type', models.CharField(choices=[('subject', 'مادة'), ('exam', 'اختبار'), ('project', 'مشروع')], max_length=10, verbose_name='نوع الدرجة')),
                ('grade_name', models.CharField(max_length=100, verbose_name='اسم الدرجة')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة')),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='الدرجة القصوى')),
                ('date_achieved', models.DateField(verbose_name='تاريخ الحصول')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='institute_app.enrollment', verbose_name='التسجيل')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='institute_app.subject', verbose_name='المادة')),
            ],
            options={
                'verbose_name': 'درجة',
                'verbose_name_plural': 'الدرجات',
            },
        ),
    ]
